user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0'

pagination_per_page: 10

categories:

  tech-blogs:
    title: 技术博客
    rss:
      unity-technology-blog:
        url: https://blog.unity.com/feed

      unreal-blog:
        url: https://www.unrealengine.com/zh-CN/rss

      jetbrains-dotnet:
        url: https://blog.jetbrains.com/dotnet/feed/

      codingnow:
        url: https://blog.codingnow.com/atom.xml

      xuanyusong:
        url: https://www.xuanyusong.com/feed

      jendrikillner:
        url: https://www.jendrikillner.com/index.xml

      gamedeveloper:
        url: https://www.gamedeveloper.com/rss.xml

      red-blob-games:
        url: https://simblob.blogspot.com/feeds/posts/default

      perfare:
        url: https://www.perfare.net/feed

      skywind:
        url: https://www.skywind.me/blog/feed

      xoofx:
        url: https://xoofx.com/feed.xml

      siggraph:
        url: https://blog.siggraph.org/feed/

      lelefeng:
        url: http://candycat1992.github.io/feed.xml

      realtimerendering:
        url: https://www.realtimerendering.com/blog/feed/

      jaihk662:
        url: https://rss.csdn.net/Jaihk662/rss/map

      killer_aery:
        url: https://feed.cnblogs.com/blog/u/434729/rss/

      blogread:
        url: https://rsshub.app/blogread/newest
        posts_show_in_home: false

  games:
    title: 游戏
    rss:
      itch-games:
        url: https://rsshub.app/itch/games/new-and-popular/featured
        posts_show_in_home: false
