site_name: Stalo's Note
site_url: https://note.stalomeow.com/
site_description: Stalo's online notebook.
repo_name: stalomeow/note
repo_url: https://github.com/stalomeow/note
edit_uri: blob/main/docs/ # do not use "edit/main/docs/"
copyright: >
  Copyright &copy; 2022-2024 Stalo. All rights reserved.<br>
  Contents are licensed under the <u><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC-BY-NC-SA 4.0</a></u> license, except when otherwise noted.


theme:
  name: material
  language: zh
  custom_dir: overrides
  favicon: assets/favicon.ico

  font:
    text: "'LXGW WenKai Screen', 'Noto Sans SC', 'Microsoft YaHei', sans-serif"
    code: "'JetBrains Mono', 'LXGW WenKai Screen', 'Noto Sans SC', 'Microsoft YaHei', sans-serif"

  icon:
    repo: fontawesome/brands/github
    logo: octicons/stack-24
    edit: material/pencil
    tag:
      default: fontawesome/solid/hashtag

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/circle-slice-4
        name: Auto Mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/circle-slice-8
        name: Light Mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/circle-outline
        name: Dark Mode

  features:
    - announce.dismiss

    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - content.action.edit

    - navigation.instant
    - navigation.instant.progress
    # - navigation.tabs
    - navigation.top
    - navigation.path
    # - navigation.indexes
    # - navigation.tracking
    # - navigation.footer
    # - navigation.sections

    - toc.follow
    # - toc.integrate

    - search.suggest
    - search.highlight
    - search.share


extra:
  social:
    - name: Home
      icon: fontawesome/solid/house
      link: https://stalomeow.com
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/stalomeow
    - name: Telegram
      icon: fontawesome/brands/telegram
      link: https://t.me/StaloMeow
    - name: Mail
      icon: fontawesome/solid/envelope
      link: mailto:stalowork@163.com
  tags: { "": default } # https://github.com/squidfunk/mkdocs-material/blob/0b38323a310d9ab9ac7fd60ad0bdae5871e42d73/src/plugins/tags/plugin.py#L146


extra_css:
  - assets/webfonts/JetBrains Mono/font.css
  - assets/webfonts/LXGW WenKai Screen/font.css
  - assets/stylesheets/theme.css
  - assets/stylesheets/feature.css
  - assets/stylesheets/temp-patch.css


extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/sponsor.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.2/es5/tex-chtml.js # 别加 mml！它会导致表格横向溢出！
  - https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.4/tex-chtml.js


markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - callouts
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      # auto_title: true
      linenums: true
      anchor_linenums: true
      use_pygments: true
      line_spans: __span # When this option is set, each line of a code block is wrapped in a span, which is essential for features like line highlighting to work correctly
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search:
      # TODO 禁用以后，运行时代码会报错，然后颜色模式切换会炸掉
      # 临时在 validate_config.py 里禁用
      # enabled: !ENV [CI, false]
      lang:
        - zh
        - en
      # TODO 分词后 highlight 有问题
      jieba_dict: docs/assets/jieba-dict.txt
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      js_files:
        - assets/javascripts/mathjax.js
        - assets/javascripts/sponsor.js
      css_files:
        - assets/webfonts/JetBrains Mono/font.css
        - assets/webfonts/LXGW WenKai Screen/font.css
        - assets/stylesheets/theme.css
        - assets/stylesheets/feature.css
        - assets/stylesheets/temp-patch.css


hooks:
  - scripts/validate_config.py
  - scripts/fetch_news.py
  - scripts/obsidian.py
  - scripts/fancybox.py


watch:
  - overrides
  - news.yml


validation:
  unrecognized_links: warn
