site_name: Stalo's Note
site_url: https://note.stalomeow.com/
site_description: Stalo's online notebook.
repo_name: stalomeow/note
repo_url: https://github.com/stalomeow/note
edit_uri: blob/main/docs/ # do not use "edit/main/docs/"
copyright: >
  Copyright &copy; 2022-2023 Stalo. All rights reserved.<br>
  Contents are licensed under the <u><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC-BY-NC-SA 4.0</a></u> license, except when otherwise noted.


theme:
  name: material
  language: zh
  custom_dir: overrides
  favicon: assets/images/favicon.ico

  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono

  icon:
    repo: fontawesome/brands/github
    logo: octicons/stack-24
    edit: material/pencil
    tag:
      default: fontawesome/solid/hashtag

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/circle-slice-4
        name: Auto Mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/circle-slice-8
        name: Light Mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/circle-outline
        name: Dark Mode

  features:
    - announce.dismiss

    - content.tooltips
    - content.code.copy
    - content.action.edit

    # TODO instant 和 MathJax 一起用目前有 bug，进下一个页面后公式排版会乱
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    # - navigation.tracking
    - navigation.footer
    # - navigation.sections

    - toc.follow
    # - toc.integrate

    - search.suggest
    - search.highlight
    - search.share


extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/stalomeow
    - name: Telegram
      icon: fontawesome/brands/telegram
      link: https://t.me/StaloMeow
    - name: Mail
      icon: fontawesome/solid/envelope
      link: mailto:me@stalomeow.com
    - name: RSS
      icon: fontawesome/solid/square-rss
      link: /feed_rss_updated.xml
  tags: { "": default } # https://github.com/squidfunk/mkdocs-material/blob/0b38323a310d9ab9ac7fd60ad0bdae5871e42d73/src/plugins/tags/plugin.py#L146


extra_css:
  - assets/webfonts/JetBrains Mono/font.css
  - assets/webfonts/LXGW WenKai Screen/font.css
  - assets/stylesheets/theme.css


extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.2/es5/tex-chtml.js # 别加 mml！它会导致表格横向溢出！
  - https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.4/tex-chtml.js


markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      # auto_title: true
      linenums: true
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search:
      # TODO 禁用以后，运行时代码会报错，然后颜色模式切换会炸掉
      # 临时在 config_validator.py 里禁用
      # enabled: !ENV [CI, false]
      lang:
        - zh
        - en
      jieba_dict: docs/assets/jieba-dict.txt
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: timeago
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
  - git-committers:
      enabled: !ENV [CI, false]
      repository: stalomeow/note
      branch: main
  - rss:
      enabled: !ENV [CI, false]
      comments_path: "#__comments"
      match_path: '^(?!.*(\/|\\)index\.md$)(?!index\.md$).*$' # 去除 **/index.md
      date_from_meta:
          default_timezone: Asia/Shanghai
  - glightbox:
      auto_caption: true
  - tags:
      tags_file: tags.md
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      js_files:
        - assets/javascripts/mathjax.js
      css_files:
        - assets/webfonts/JetBrains Mono/font.css
        - assets/webfonts/LXGW WenKai Screen/font.css
        - assets/stylesheets/theme.css


hooks:
  - scripts/config_validator.py
  - scripts/index_validator.py


nav:
  - 首页:
    - index.md
    - 标签: tags.md
    - 网站资源: website-res.md
    - 在线工具: online-tools.md
  - 基础知识:
    - basic/index.md
    - 高中数学:
      - 三角恒等式: basic/high-school-math/trigonometric-function-identity.md
      - 指数函数与其反函数的交点个数: basic/high-school-math/intersection-point-of-exp-and-its-inv.md
    - 高等数学:
      - 积分公式: basic/advanced-math/integral-formula.md
      - 微分方程: basic/advanced-math/differential-equation.md
      - 梯度、散度、旋度: basic/advanced-math/grad-div-curl.md
      - 傅里叶级数实现本轮画图: basic/advanced-math/fourier-epicycles.md
    - 线性代数:
      - 矩阵: basic/linear-algebra/matrix.md
      - 行列式: basic/linear-algebra/determinant.md
      - 四元数: basic/linear-algebra/quaternion.md
    - 概率论与数理统计:
      - 随机变量及其概率分布: basic/probability-statistics/random-var-and-prob-distribution.md
      - 随机变量的数字特征: basic/probability-statistics/numerical-characteristics-of-random-var.md
      - 大数定律和中心极限定理: basic/probability-statistics/lln-and-clt.md
      - 参数估计: basic/probability-statistics/parameter-estimation.md
    - 高中英语作文框架: basic/english/high-school-composition-framework.md
  - 计算机科学:
    - cs/index.md
    - 编程语言:
      - C/C++:
        - 函数调用约定: cs/pl/c-cpp/calling-convention.md
        - STL 相关: cs/pl/c-cpp/stl.md
        - C++ 11 相关: cs/pl/c-cpp/cpp-11.md
      - C#:
        - 弱引用: cs/pl/csharp/weak-references.md
        - 模式匹配: cs/pl/csharp/pattern-matching.md
        - GC.KeepAlive: cs/pl/csharp/gc-keep-alive.md
        - Delegate Marshalling: cs/pl/csharp/delegate-marshalling.md
      - Python:
        - Python 基础: cs/pl/python/basic.md
        - 执行一个模块: cs/pl/python/run-a-module.md
        - 多版本和虚拟环境: cs/pl/python/multi-versions-and-venv.md
        - 生成 requirements.txt: cs/pl/python/generate-requirements.md
        - 卸载 Python: cs/pl/python/uninstall.md
      - JS/TS:
        - 写一个简易 jQuery: cs/pl/js-ts/write-a-mini-jquery.md
      - Go:
        - Go 基础: cs/pl/go/basic.md
    - 数据结构与算法:
      - cs/ds-and-algorithm/index.md
      - 数组: cs/ds-and-algorithm/array.md
      - 链表: cs/ds-and-algorithm/linked-list.md
      - 搜索:
        - DFS: cs/ds-and-algorithm/search/dfs.md
        - BFS: cs/ds-and-algorithm/search/bfs.md
        - A*: cs/ds-and-algorithm/search/a-star.md
        - 回溯法: cs/ds-and-algorithm/search/backtracking.md
        - Dancing Links: cs/ds-and-algorithm/search/dancing-links.md
      - 字符串:
        - KMP: cs/ds-and-algorithm/string/kmp.md
        - Rabin-Karp: cs/ds-and-algorithm/string/rabin-karp.md
      - 图论:
        - 树:
          - 树相关概念: cs/ds-and-algorithm/graph/tree/tree-concept.md
          - 二叉树遍历: cs/ds-and-algorithm/graph/tree/binary-tree-traversal.md
          - 完全二叉树: cs/ds-and-algorithm/graph/tree/complete-binary-tree.md
          - 从遍历序列构建二叉树: cs/ds-and-algorithm/graph/tree/construct-binary-tree-from-traversal.md
          - 二叉搜索树: cs/ds-and-algorithm/graph/tree/binary-search-tree.md
          - 并查集: cs/ds-and-algorithm/graph/tree/disjoint-set.md
          - Huffman 树: cs/ds-and-algorithm/graph/tree/huffman-tree.md
        - 最小生成树: cs/ds-and-algorithm/graph/minimum-spanning-tree.md
      - 杂项: cs/ds-and-algorithm/misc.md
    - 计算机图形学:
      - cs/cg/index.md
      - Half Lambert 勘误: cs/cg/half-lambert-corrigenda.md
      - 法线贴图压缩: cs/cg/normal-map-compression.md
      - 颜色空间: cs/cg/color-space.md
      - NPR: # Non-photorealistic rendering
        - 卡通角色渲染: cs/cg/npr/character.md
        - 仿星穹铁道的角色渲染: cs/cg/npr/hsr-character.md
      - 逆向:
        - 提取 WebGL Shaders: cs/cg/reverse/dump-webgl-shaders.md
        - 反编译 DXBC: cs/cg/reverse/decompile-dxbc.md
        - 用 RenderDoc 和模拟器抓帧安卓手游: cs/cg/reverse/renderdoc-capture-frame-in-emulator.md
    - GAMES 课程: # GAMES: Graphics And Mixed Environment Symposium
      - 101. 现代计算机图形学入门:
        - cs/games-course/101/index.md
        - Overview of Computer Graphics: cs/games-course/101/lecture-01.md
        - Review of Linear Algebra: cs/games-course/101/lecture-02.md
        - Transformation: cs/games-course/101/lecture-03.md
        - Transformation Cont.: cs/games-course/101/lecture-04.md
        - Rasterization 1 (Triangles): cs/games-course/101/lecture-05.md
        - Rasterization 2 (Antialiasing and Z-Buffering): cs/games-course/101/lecture-06.md
        - Shading 1 (Illumination, Shading and Graphics Pipeline): cs/games-course/101/lecture-07.md
        - Shading 2 (Shading, Pipeline and Texture Mapping): cs/games-course/101/lecture-08.md
        - Shading 3 (Texture Mapping Cont.): cs/games-course/101/lecture-09.md
        - Geometry 1 (Introduction): cs/games-course/101/lecture-10.md
        - Geometry 2 (Curves and Surfaces): cs/games-course/101/lecture-11.md
        - Geometry 3: cs/games-course/101/lecture-12.md
        - Ray Tracing 1: cs/games-course/101/lecture-13.md
        - Ray Tracing 2: cs/games-course/101/lecture-14.md
        - Ray Tracing 3: cs/games-course/101/lecture-15.md
        - Ray Tracing 4: cs/games-course/101/lecture-16.md
        - Materials and Appearances: cs/games-course/101/lecture-17.md
        - Advanced Topics in Rendering: cs/games-course/101/lecture-18.md
        - Cameras, Lenses and Light Fields: cs/games-course/101/lecture-19.md
        - Color and Perception: cs/games-course/101/lecture-20.md
        - Animation: cs/games-course/101/lecture-21.md
        - Animation Cont.: cs/games-course/101/lecture-22.md
      - 104. 现代游戏引擎:
        - cs/games-course/104/index.md
        - From Getting Started To Practice: cs/games-course/104/lecture-01.md
        - Layered Architecture of Game Engine: cs/games-course/104/lecture-02.md
        - How to Build a Game World: cs/games-course/104/lecture-03.md
        - Rendering:
          - Rendering on Game Engine: cs/games-course/104/lecture-04.md
          - Lighting, Materials and Shaders: cs/games-course/104/lecture-05.md
          - The Challenges and Fun of Rendering the Beautiful Mother Nature: cs/games-course/104/lecture-06.md
          - Render Pipeline, Post-processing and Everything: cs/games-course/104/lecture-07.md
        - Animation System:
          - Basics of Animation Technology: cs/games-course/104/lecture-08.md
          - Advanced Animation Technology: cs/games-course/104/lecture-09.md
        - Physics System:
          - Basic Concepts: cs/games-course/104/lecture-10.md
          - Applications: cs/games-course/104/lecture-11.md
        - Effects: cs/games-course/104/lecture-12.md
        - Tool Chains:
          - Basics: cs/games-course/104/lecture-13.md
          - Applications & Advanced Topic: cs/games-course/104/lecture-14.md
        - Gameplay Systems:
          - Complexity and Building Blocks: cs/games-course/104/lecture-15.md
          - Basic Artificial Intelligence: cs/games-course/104/lecture-16.md
          - Advanced Artificial Intelligence: cs/games-course/104/lecture-17.md
        - Online Gaming Architecture:
          - Fundamentals: cs/games-course/104/lecture-18.md
          - Advanced Topic: cs/games-course/104/lecture-19.md
        - Data-Oriented Programming and Job System: cs/games-course/104/lecture-20.md
        - Dynamic Global Illumination and Lumen: cs/games-course/104/lecture-21.md
        - GPU Driven Geometry Pipeline - Nanite: cs/games-course/104/lecture-22.md
    - 命令行工具:
      - Aria2: cs/cmd-tool/aria2.md
      - Git: cs/cmd-tool/git.md
    - 腾讯游戏客户端公开课:
      - 简历制作 & 面试辅导: cs/tencent-game-client-course/interview-resume.md
    - Misc:
      - Unicode: cs/misc/unicode.md
      - 解决 CAS 时的 ABA 问题: cs/misc/solve-cas-aba-problem.md
  - Unity 开发:
    - unity/index.md
    - 图形开发:
      - 平滑模型法线: unity/graphics/smooth-model-normals.md
      - 强制让 SRP Batch 支持 Multipass Shader: unity/graphics/srp-batch-multipass-shader.md
      - Shader 相关:
        - Material Property Drawer: unity/graphics/shader/material-property-drawer.md
    - 编辑器开发:
      - IL Post-Process: unity/editor/il-post-process.md
      - 类似 Animation Window 的 Record 和 Preview 功能: unity/editor/animation-window-record-preview-impl.md
    - 源码分析:
      - Unity UI:
        - TODO: unity/src-analysis/ugui/placeholder.md
      - Universal RP:
        - TODO: unity/src-analysis/urp/placeholder.md
    - 技术分析:
      - Full Generic Sharing: unity/tech-analysis/full-generic-sharing.md
    - 解决方案:
      - unity/troubleshooting/index.md
      - GetComponentInParent on PrefabAsset returns null: unity/troubleshooting/get-component-in-parent-on-prefab-asset-returns-null.md
  - Unreal 开发:
    - unreal/index.md
    - 编译 UE4 源码: unreal/compile-ue4-source-code.md
  - Misc:
    - misc/index.md
    - 面试相关: misc/interview.md
    - 网页中嵌入 b 站视频: misc/bilibili-iframe.md
    - Win11 微软输入法快捷键冲突: misc/win11-ms-input-shortcuts-conflict.md
    - 下载微信视频号的视频: misc/download-wechat-video.md
