site_name: Stalo's Note
site_url: https://note.stalomeow.com/
site_description: Stalo's online notebook.
repo_name: stalomeow/note
repo_url: https://github.com/stalomeow/note
edit_uri: blob/main/docs/ # do not use "edit/main/docs/"
copyright: >
  Copyright &copy; 2022-2023 Stalo. All rights reserved.<br>
  Contents are licensed under the <u><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC-BY-NC-SA 4.0</a></u> license, except when otherwise noted.


theme:
  name: material
  language: zh
  custom_dir: overrides
  favicon: &site-icon assets/images/favicon.ico

  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono

  icon:
    repo: fontawesome/brands/github
    logo: octicons/stack-24
    edit: material/pencil
    tag:
      default: fontawesome/solid/hashtag

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/circle-slice-4
        name: Auto Mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/circle-slice-8
        name: Light Mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/circle-outline
        name: Dark Mode

  features:
    - announce.dismiss

    - content.tooltips
    - content.code.copy
    - content.action.edit

    # TODO instant 和 MathJax 一起用目前有 bug，进下一个页面后公式排版会乱
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    # - navigation.tracking
    - navigation.footer
    # - navigation.sections

    - toc.follow
    # - toc.integrate

    - search.suggest
    - search.highlight
    - search.share


extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/stalomeow
    - name: Telegram
      icon: fontawesome/brands/telegram
      link: https://t.me/StaloMeow
    - name: Mail
      icon: fontawesome/solid/envelope
      link: mailto:me@stalomeow.com
  tags: { "": default } # https://github.com/squidfunk/mkdocs-material/blob/0b38323a310d9ab9ac7fd60ad0bdae5871e42d73/src/plugins/tags/plugin.py#L146


extra_css:
  - assets/webfonts/JetBrains Mono/font.css
  - assets/webfonts/LXGW WenKai Screen/font.css
  - assets/stylesheets/theme.css


extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.2/es5/tex-chtml.js # 别加 mml！它会导致表格横向溢出！
  - https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.4/tex-chtml.js


markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      # auto_title: true
      linenums: true
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search:
      # TODO 禁用以后，运行时代码会报错，然后颜色模式切换会炸掉
      # 临时在 config_validator.py 里禁用
      # enabled: !ENV [CI, false]
      lang:
        - zh
        - en
      jieba_dict: docs/assets/jieba-dict.txt
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: timeago
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - blog/** # 不要处理 Blog
        - news/** # 不要处理 News
  - git-committers:
      enabled: !ENV [CI, false]
      repository: stalomeow/note
      branch: main
      exclude:
        - blog/** # 不要处理 Blog
        - news/** # 不要处理 News
  - rss:
      enabled: !ENV [CI, false]
      match_path: 'blog/posts/.*'
      comments_path: "#__comments"
      date_from_meta:
          as_creation: date
          default_timezone: Asia/Shanghai
      categories:
        - categories
      image: *site-icon
  - glightbox:
      auto_caption: true
  - tags:
      tags_file: tags.md
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      js_files:
        - assets/javascripts/mathjax.js
      css_files:
        - assets/webfonts/JetBrains Mono/font.css
        - assets/webfonts/LXGW WenKai Screen/font.css
        - assets/stylesheets/theme.css
  - blog:
      enabled: true
      blog_toc: false # TODO 中文 toc 有问题，很多 id 都是 #_1
      archive: true
      archive_toc: false # TODO 中文 toc 有问题，很多 id 都是 #_1
      archive_date_format: yyyy 年 MM 月
      archive_url_date_format: yyyy/MM
      categories: true
      categories_toc: false # TODO 中文 toc 有问题，很多 id 都是 #_1
      authors: true
      post_date_format: yyyy-MM-dd
      post_readtime: true
      post_url_format: "posts/{file}-{date}"
      post_url_date_format: yyyy-MM-dd
      post_excerpt: required
      post_excerpt_max_authors: 0
      pagination: true
      pagination_per_page: 10
      pagination_format: "~2~"
      pagination_if_single_page: true
      pagination_keep_content: false


hooks:
  - scripts/config_validator.py
  - scripts/index_validator.py
  - scripts/news_fetcher.py


nav:
  - 首页:
    - index.md
    - 标签: tags.md
    - 网站资源: website-res.md
    - 在线工具: online-tools.md
  - 资讯:
    - news/index.md
  - 博客:
    - blog/index.md
  - 课程笔记:
    - course/index.md
    - 概率论与数理统计:
      - 随机变量及其概率分布: course/probability-statistics/random-var-and-prob-distribution.md
      - 随机变量的数字特征: course/probability-statistics/numerical-characteristics-of-random-var.md
      - 大数定律和中心极限定理: course/probability-statistics/lln-and-clt.md
      - 参数估计: course/probability-statistics/parameter-estimation.md
    - 线性代数:
      - 矩阵: course/linear-algebra/matrix.md
      - 行列式: course/linear-algebra/determinant.md
      - 四元数: course/linear-algebra/quaternion.md
    - 高等数学:
      - 积分公式: course/advanced-math/integral-formula.md
      - 微分方程: course/advanced-math/differential-equation.md
      - 梯度、散度、旋度: course/advanced-math/grad-div-curl.md
    - 腾讯游戏客户端公开课:
      - 简历制作 & 面试辅导: course/tencent-game-client-course/interview-resume.md
    - 高中数学:
      - 三角恒等式: course/high-school-math/trigonometric-function-identity.md
      - 指数函数与其反函数的交点个数: course/high-school-math/intersection-point-of-exp-and-its-inv.md
    - 高中英语作文框架: course/english/high-school-composition-framework.md
  - 数据结构与算法:
    - algorithm/index.md
    - 数组: algorithm/array.md
    - 链表: algorithm/linked-list.md
    - 搜索:
      - DFS: algorithm/search/dfs.md
      - BFS: algorithm/search/bfs.md
      - A*: algorithm/search/a-star.md
      - 回溯法: algorithm/search/backtracking.md
      - Dancing Links: algorithm/search/dancing-links.md
    - 字符串:
      - KMP: algorithm/string/kmp.md
      - Rabin-Karp: algorithm/string/rabin-karp.md
    - 图论:
      - 树:
        - 树相关概念: algorithm/graph/tree/tree-concept.md
        - 二叉树遍历: algorithm/graph/tree/binary-tree-traversal.md
        - 完全二叉树: algorithm/graph/tree/complete-binary-tree.md
        - 从遍历序列构建二叉树: algorithm/graph/tree/construct-binary-tree-from-traversal.md
        - 二叉搜索树: algorithm/graph/tree/binary-search-tree.md
        - 并查集: algorithm/graph/tree/disjoint-set.md
        - Huffman 树: algorithm/graph/tree/huffman-tree.md
      - 最小生成树: algorithm/graph/minimum-spanning-tree.md
    - 杂项: algorithm/misc.md
  - GAMES:
    - games/index.md
    - 101. 现代计算机图形学入门:
      - games/101/index.md
      - Overview of Computer Graphics: games/101/lecture-01.md
      - Review of Linear Algebra: games/101/lecture-02.md
      - Transformation: games/101/lecture-03.md
      - Transformation Cont.: games/101/lecture-04.md
      - Rasterization 1 (Triangles): games/101/lecture-05.md
      - Rasterization 2 (Antialiasing and Z-Buffering): games/101/lecture-06.md
      - Shading 1 (Illumination, Shading and Graphics Pipeline): games/101/lecture-07.md
      - Shading 2 (Shading, Pipeline and Texture Mapping): games/101/lecture-08.md
      - Shading 3 (Texture Mapping Cont.): games/101/lecture-09.md
      - Geometry 1 (Introduction): games/101/lecture-10.md
      - Geometry 2 (Curves and Surfaces): games/101/lecture-11.md
      - Geometry 3: games/101/lecture-12.md
      - Ray Tracing 1: games/101/lecture-13.md
      - Ray Tracing 2: games/101/lecture-14.md
      - Ray Tracing 3: games/101/lecture-15.md
      - Ray Tracing 4: games/101/lecture-16.md
      - Materials and Appearances: games/101/lecture-17.md
      - Advanced Topics in Rendering: games/101/lecture-18.md
      - Cameras, Lenses and Light Fields: games/101/lecture-19.md
      - Color and Perception: games/101/lecture-20.md
      - Animation: games/101/lecture-21.md
      - Animation Cont.: games/101/lecture-22.md
    - 104. 现代游戏引擎:
      - games/104/index.md
      - From Getting Started To Practice: games/104/lecture-01.md
      - Layered Architecture of Game Engine: games/104/lecture-02.md
      - How to Build a Game World: games/104/lecture-03.md
      - Rendering:
        - Rendering on Game Engine: games/104/lecture-04.md
        - Lighting, Materials and Shaders: games/104/lecture-05.md
        - The Challenges and Fun of Rendering the Beautiful Mother Nature: games/104/lecture-06.md
        - Render Pipeline, Post-processing and Everything: games/104/lecture-07.md
      - Animation System:
        - Basics of Animation Technology: games/104/lecture-08.md
        - Advanced Animation Technology: games/104/lecture-09.md
      - Physics System:
        - Basic Concepts: games/104/lecture-10.md
        - Applications: games/104/lecture-11.md
      - Effects: games/104/lecture-12.md
      - Tool Chains:
        - Basics: games/104/lecture-13.md
        - Applications & Advanced Topic: games/104/lecture-14.md
      - Gameplay Systems:
        - Complexity and Building Blocks: games/104/lecture-15.md
        - Basic Artificial Intelligence: games/104/lecture-16.md
        - Advanced Artificial Intelligence: games/104/lecture-17.md
      - Online Gaming Architecture:
        - Fundamentals: games/104/lecture-18.md
        - Advanced Topic: games/104/lecture-19.md
      - Data-Oriented Programming and Job System: games/104/lecture-20.md
      - Dynamic Global Illumination and Lumen: games/104/lecture-21.md
      - GPU Driven Geometry Pipeline - Nanite: games/104/lecture-22.md
  - 技术积累:
    - accum/index.md
    - 编程语言:
      - C/C++:
        - 函数调用约定: accum/pl/c-cpp/calling-convention.md
        - STL 相关: accum/pl/c-cpp/stl.md
        - C++ 11 相关: accum/pl/c-cpp/cpp-11.md
      - C#:
        - 弱引用: accum/pl/csharp/weak-references.md
        - 模式匹配: accum/pl/csharp/pattern-matching.md
        - GC.KeepAlive: accum/pl/csharp/gc-keep-alive.md
        - Delegate Marshalling: accum/pl/csharp/delegate-marshalling.md
      - Python:
        - Python 基础: accum/pl/python/basic.md
        - 执行一个模块: accum/pl/python/run-a-module.md
        - 多版本和虚拟环境: accum/pl/python/multi-versions-and-venv.md
      - Go:
        - Go 基础: accum/pl/go/basic.md
    - 计算机图形学:
      - accum/cg/index.md
      - Half Lambert 勘误: accum/cg/half-lambert-corrigenda.md
      - 颜色空间: accum/cg/color-space.md
      - NPR: # Non-photorealistic rendering
        - 卡通角色渲染: accum/cg/npr/character.md
    - 命令行:
      - Aria2: accum/cmd/aria2.md
      - Git: accum/cmd/git.md
    - Unity:
      - Shader 相关:
        - Material Property Drawer: accum/unity/shader/material-property-drawer.md
      - 源码分析:
        - Unity UI:
          - TODO: accum/unity/src-analysis/ugui/placeholder.md
        - Universal RP:
          - TODO: accum/unity/src-analysis/urp/placeholder.md
      - 技术分析:
        - Full Generic Sharing: accum/unity/tech-analysis/full-generic-sharing.md
    - Misc:
      - Unicode: accum/misc/unicode.md
