site_name: March 7th KM
site_url: https://km.stalomeow.com/
site_description: March 7th KM
repo_name: stalomeow/note
repo_url: https://github.com/stalomeow/note
edit_uri: blob/main/docs/ # do not use "edit/main/docs/"

theme:
  name: material
  language: zh
  custom_dir: overrides
  favicon: https://stalomeow.com/favicon.ico

  font:
    text: "'LXGW WenKai Screen', 'Noto Sans SC', 'Microsoft YaHei', sans-serif"
    code: "'Cascadia Mono', 'LXGW WenKai Screen', 'Noto Sans SC', 'Microsoft YaHei', sans-serif"

  icon:
    repo: fontawesome/brands/github
    logo: octicons/stack-24
    edit: material/pencil

  palette:
    scheme: slate
    primary: black

  features:
    - announce.dismiss

    - content.tooltips
    - content.code.copy
    # - content.code.annotate
    - content.action.edit
    - content.tabs.link

    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    # - navigation.tabs
    - navigation.top
    - navigation.path
    # - navigation.indexes
    # - navigation.tracking
    # - navigation.footer
    - navigation.sections

    - toc.follow
    # - toc.integrate

    - search.suggest
    - search.highlight
    - search.share


extra:
  analytics:
    provider: google
    property: G-RQ5JMJBFBP


extra_css:
  - assets/webfonts/Cascadia Mono/font.css
  - assets/webfonts/LXGW WenKai Screen/font.css
  - assets/stylesheets/theme.css
  - assets/stylesheets/feature.css
  - assets/stylesheets/temp-patch.css


extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/comments.js
  - assets/javascripts/links.js
  - https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.7/tex-chtml.js


markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - callouts
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      # auto_title: true
      # linenums: true
      # anchor_linenums: true
      # line_spans: __span # When this option is set, each line of a code block is wrapped in a span, which is essential for features like line highlighting to work correctly
      use_pygments: true

      # https://facelessuser.github.io/pymdown-extensions/extensions/highlight/#extended-pygments-lexer-options
      extend_pygments_lang:
        - name: antlr4
          lang: antlr
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      # 生成可读的 unicode slug
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.slugify
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - toc:
      # https://python-markdown.github.io/extensions/toc/
      permalink: true
      separator: "-"
      # 生成可读的 unicode slug
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.slugify
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
  - search:
      lang: zh
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      js_files:
        - assets/javascripts/mathjax.js
        - assets/javascripts/comments.js
        - assets/javascripts/links.js
      css_files:
        - assets/webfonts/Cascadia Mono/font.css
        - assets/webfonts/LXGW WenKai Screen/font.css
        - assets/stylesheets/theme.css
        - assets/stylesheets/feature.css
        - assets/stylesheets/temp-patch.css
  - redirects:
      redirect_maps:
        'blog/posts/unity-hsr-dream-ticker-2024-02-18.md': 'obsidian-vault/星穹铁道/复刻星穹铁道 2.0 梦境迷钟.md'
        'blog/posts/high-quality-toon-bloom-2024-03-05.md': 'obsidian-vault/星穹铁道/仿星铁渲染：Bloom.md'
        'blog/posts/main-light-per-object-shadow-2024-03-15.md': 'obsidian-vault/星穹铁道/仿星铁渲染：主光源角色阴影.md'
        'basic/advanced-math/fourier-epicycles.md': 'obsidian-vault/Misc/傅里叶级数实现本轮画图.md'


hooks:
  - scripts/dev.py
  - scripts/obsidian.py
  - scripts/fancybox.py
  - scripts/copyright.py
  - scripts/links.py
  - scripts/rss.py


watch:
  - overrides


# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  links:
    anchors: warn
    unrecognized_links: warn
