site_name: Stalo's Note
site_url: https://note.stalomeow.com/
site_description: Stalo's online notebook.
repo_name: stalomeow/note
repo_url: https://github.com/stalomeow/note
edit_uri: blob/main/docs/ # do not use "edit/main/docs/"
copyright: >
  Copyright &copy; 2022-2024 Stalo. All rights reserved.<br>
  Contents are licensed under the <u><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC-BY-NC-SA 4.0</a></u> license, except when otherwise noted.


theme:
  name: material
  language: zh
  custom_dir: overrides
  favicon: &site-icon assets/images/favicon.ico

  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono

  icon:
    repo: fontawesome/brands/github
    logo: octicons/stack-24
    edit: material/pencil
    tag:
      default: fontawesome/solid/hashtag

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/circle-slice-4
        name: Auto Mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/circle-slice-8
        name: Light Mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/circle-outline
        name: Dark Mode

  features:
    - announce.dismiss

    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - content.action.edit

    # TODO instant 和 MathJax 一起用目前有 bug，进下一个页面后公式排版会乱
    # - navigation.instant
    # - navigation.instant.progress
    # - navigation.tabs
    - navigation.top
    - navigation.path
    # - navigation.indexes
    # - navigation.tracking
    - navigation.footer
    # - navigation.sections

    - toc.follow
    # - toc.integrate

    - search.suggest
    - search.highlight
    - search.share


extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/stalomeow
    - name: Telegram
      icon: fontawesome/brands/telegram
      link: https://t.me/StaloMeow
    - name: Mail
      icon: fontawesome/solid/envelope
      link: mailto:stalowork@163.com
    - name: Blog RSS
      icon: fontawesome/solid/square-rss
      link: /feed_rss_created.xml
  tags: { "": default } # https://github.com/squidfunk/mkdocs-material/blob/0b38323a310d9ab9ac7fd60ad0bdae5871e42d73/src/plugins/tags/plugin.py#L146


extra_css:
  - assets/webfonts/JetBrains Mono/font.css
  - assets/webfonts/LXGW WenKai Screen/font.css
  - assets/stylesheets/theme.css
  - assets/stylesheets/feature.css
  - assets/stylesheets/temp-patch.css


extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.2/es5/tex-chtml.js # 别加 mml！它会导致表格横向溢出！
  - https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.4/tex-chtml.js


markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      # auto_title: true
      linenums: true
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search:
      # TODO 禁用以后，运行时代码会报错，然后颜色模式切换会炸掉
      # 临时在 config_validator.py 里禁用
      # enabled: !ENV [CI, false]
      lang:
        - zh
        - en
      # TODO 分词后 highlight 有问题
      jieba_dict: docs/assets/jieba-dict.txt
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: timeago
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - blog/** # 不要处理 Blog
        - news/** # 不要处理 News
  - git-committers:
      enabled: !ENV [CI, false]
      repository: stalomeow/note
      branch: main
      exclude:
        - blog/** # 不要处理 Blog
        - news/** # 不要处理 News
  - rss:
      enabled: !ENV [CI, false]
      match_path: 'blog/posts/.*'
      comments_path: "#__comments"
      date_from_meta:
          as_creation: date
          default_timezone: Asia/Shanghai
      categories:
        - categories
      image: *site-icon
  - glightbox:
      auto_caption: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      js_files:
        - assets/javascripts/mathjax.js
      css_files:
        - assets/webfonts/JetBrains Mono/font.css
        - assets/webfonts/LXGW WenKai Screen/font.css
        - assets/stylesheets/theme.css
        - assets/stylesheets/feature.css
        - assets/stylesheets/temp-patch.css
  - blog:
      enabled: true
      blog_toc: false # TODO 中文 toc 有问题，很多 id 都是 #_1
      archive: true
      archive_toc: false # TODO 中文 toc 有问题，很多 id 都是 #_1
      archive_date_format: yyyy 年 MM 月
      archive_url_date_format: yyyy/MM
      categories: true
      categories_toc: false # TODO 中文 toc 有问题，很多 id 都是 #_1
      authors: true
      post_date_format: yyyy-MM-dd
      post_readtime: true
      post_readtime_words_per_minute: 180
      post_url_format: "posts/{file}-{date}"
      post_url_date_format: yyyy-MM-dd
      post_excerpt: required
      post_excerpt_max_authors: 0
      pagination: true
      pagination_per_page: 10
      pagination_format: "~2~"
      pagination_if_single_page: true
      pagination_keep_content: false


hooks:
  - scripts/config_validator.py
  - scripts/news_fetcher.py


nav:
  - index.md
  - 网站资源: website-res.md
  - 博客:
    - blog/index.md
  - RSS 阅读:
    - news/index.md
  - 基础学科:
    - 概率论与数理统计:
      - 随机变量及其概率分布: basic/probability-statistics/random-var-and-prob-distribution.md
      - 随机变量的数字特征: basic/probability-statistics/numerical-characteristics-of-random-var.md
      - 大数定律和中心极限定理: basic/probability-statistics/lln-and-clt.md
      - 参数估计: basic/probability-statistics/parameter-estimation.md
    - 线性代数:
      - 矩阵: basic/linear-algebra/matrix.md
      - 行列式: basic/linear-algebra/determinant.md
      - 四元数: basic/linear-algebra/quaternion.md
    - 高等数学:
      - 积分公式: basic/advanced-math/integral-formula.md
      - 微分方程: basic/advanced-math/differential-equation.md
      - 梯度、散度、旋度: basic/advanced-math/grad-div-curl.md
    - 高中数学:
      - 三角恒等式: basic/high-school-math/trigonometric-function-identity.md
      - 指数函数与其反函数的交点个数: basic/high-school-math/intersection-point-of-exp-and-its-inv.md
    - 高中英语作文框架: basic/english/high-school-composition-framework.md
  - 计算机:
    - 编程语言:
      - C/C++:
        - 函数调用约定: cs/lang/c-cpp/calling-convention.md
        - STL 相关: cs/lang/c-cpp/stl.md
        - C++ 11 相关: cs/lang/c-cpp/cpp-11.md
      - C#:
        - 命名规范: cs/lang/csharp/naming-convention.md
        - 弱引用: cs/lang/csharp/weak-references.md
        - 模式匹配: cs/lang/csharp/pattern-matching.md
        - GC.KeepAlive: cs/lang/csharp/gc-keep-alive.md
        - Delegate Marshalling: cs/lang/csharp/delegate-marshalling.md
      - Python:
        - Python 基础: cs/lang/python/basic.md
        - 执行一个模块: cs/lang/python/run-a-module.md
        - 多版本和虚拟环境: cs/lang/python/multi-versions-and-venv.md
      - Go:
        - Go 基础: cs/lang/go/basic.md
    - 数据结构与算法:
      - 学习资料: cs/algorithm/res.md
      - 数组: cs/algorithm/array.md
      - 链表: cs/algorithm/linked-list.md
      - 搜索:
        - DFS: cs/algorithm/search/dfs.md
        - BFS: cs/algorithm/search/bfs.md
        - A*: cs/algorithm/search/a-star.md
        - 回溯法: cs/algorithm/search/backtracking.md
        - Dancing Links: cs/algorithm/search/dancing-links.md
      - 字符串:
        - KMP: cs/algorithm/string/kmp.md
        - Rabin-Karp: cs/algorithm/string/rabin-karp.md
      - 树:
        - 基本概念: cs/algorithm/tree/basic-concept.md
        - 二叉树遍历: cs/algorithm/tree/binary-tree-traversal.md
        - 完全二叉树: cs/algorithm/tree/complete-binary-tree.md
        - 从遍历序列构建二叉树: cs/algorithm/tree/construct-binary-tree-from-traversal.md
        - 二叉搜索树: cs/algorithm/tree/binary-search-tree.md
        - 并查集: cs/algorithm/tree/disjoint-set.md
        - Huffman 树: cs/algorithm/tree/huffman-tree.md
      - 图:
        - 基本概念: cs/algorithm/graph/basic-concept.md
        - 连通分量个数: cs/algorithm/graph/number-of-connected-components.md
        - 最小生成树: cs/algorithm/graph/minimum-spanning-tree.md
        - 拓扑排序: cs/algorithm/graph/topological-sort.md
        - 关键路径: cs/algorithm/graph/critical-path.md
        - 判断是否有环: cs/algorithm/graph/detect-cycles.md
        - 最短路: cs/algorithm/graph/shortest-path.md
      - 排序:
        - 各种排序对比: cs/algorithm/sort/compare.md
        - 插入:
          - 直接插入排序: cs/algorithm/sort/insert/straight-insertion-sort.md
          - 希尔排序: cs/algorithm/sort/insert/shell-sort.md
        - 交换:
          - 冒泡排序: cs/algorithm/sort/swap/bubble-sort.md
          - 快速排序: cs/algorithm/sort/swap/quick-sort.md
        - 选择:
          - 堆排序: cs/algorithm/sort/select/heap-sort.md
      - 杂项: cs/algorithm/misc.md
    - 数字电路与逻辑设计:
      - 数制与编码: cs/digital-electronics/number-system-and-coding.md
    - 计算机图形学:
      - Half Lambert 勘误: cs/cg/half-lambert-corrigenda.md
      - 颜色空间: cs/cg/color-space.md
      - NPR: # Non-photorealistic rendering
        - 卡通角色渲染: cs/cg/npr/character.md
    - 命令行:
      - Aria2: cs/cmd/aria2.md
      - Git: cs/cmd/git.md
    - Unicode: cs/unicode.md
    - 简历 & 面试: cs/resume-and-interview.md
  - Unity:
    - Shader 相关:
      - 平台差异: unity/shader/platform-differences.md
      - Material Property Drawer: unity/shader/material-property-drawer.md
      - 常用 Render State 属性 UI: unity/shader/common-render-state-props-ui.md
    - 源码分析:
      - Unity UI:
        - TODO: unity/src-analysis/ugui/placeholder.md
      - Universal RP:
        - TODO: unity/src-analysis/urp/placeholder.md
    - 技术分析:
      - Full Generic Sharing: unity/tech-analysis/full-generic-sharing.md
    - 优化:
      - 优化迭代和协程的 GC: unity/optimization/iteration-coroutine-gc.md
  - GAMES 笔记:
    - 101. 现代计算机图形学入门:
      - 课程介绍: games/101/intro.md
      - Overview of Computer Graphics: games/101/lecture-01.md
      - Review of Linear Algebra: games/101/lecture-02.md
      - Transformation: games/101/lecture-03-04.md
      - Rasterization:
        - Triangles: games/101/lecture-05.md
        - Antialiasing and Z-Buffering: games/101/lecture-06.md
      - Shading:
        - Illumination, Shading and Graphics Pipeline: games/101/lecture-07.md
        - Shading, Pipeline and Texture Mapping: games/101/lecture-08-09.md
      - Geometry:
        - Introduction: games/101/lecture-10.md
        - Curves and Surfaces: games/101/lecture-11.md
        - Mesh Operations and Shadow Mapping: games/101/lecture-12.md
      - Ray Tracing: games/101/lecture-13-14-15-16.md
      - Materials and Appearances: games/101/lecture-17.md
      - Advanced Topics in Rendering: games/101/lecture-18.md
      - Cameras, Lenses and Light Fields: games/101/lecture-19.md
      - Color and Perception: games/101/lecture-20.md
      - Animation: games/101/lecture-21-22.md
    - 104. 现代游戏引擎:
      - 课程介绍: games/104/intro.md
      - From Getting Started To Practice: games/104/lecture-01.md
      - Layered Architecture of Game Engine: games/104/lecture-02.md
      - How to Build a Game World: games/104/lecture-03.md
      - Rendering:
        - Rendering on Game Engine: games/104/lecture-04.md
        - Lighting, Materials and Shaders: games/104/lecture-05.md
        - The Challenges and Fun of Rendering the Beautiful Mother Nature: games/104/lecture-06.md
        - Render Pipeline, Post-processing and Everything: games/104/lecture-07.md
      - Animation System:
        - Basics of Animation Technology: games/104/lecture-08.md
        - Advanced Animation Technology: games/104/lecture-09.md
      - Physics System:
        - Basic Concepts: games/104/lecture-10.md
        - Applications: games/104/lecture-11.md
      - Effects: games/104/lecture-12.md
      - Tool Chains:
        - Basics: games/104/lecture-13.md
        - Applications & Advanced Topic: games/104/lecture-14.md
      - Gameplay Systems:
        - Complexity and Building Blocks: games/104/lecture-15.md
        - Basic Artificial Intelligence: games/104/lecture-16.md
        - Advanced Artificial Intelligence: games/104/lecture-17.md
      - Online Gaming Architecture:
        - Fundamentals: games/104/lecture-18.md
        - Advanced Topic: games/104/lecture-19.md
      - Data-Oriented Programming and Job System: games/104/lecture-20.md
      - Dynamic Global Illumination and Lumen: games/104/lecture-21.md
      - GPU Driven Geometry Pipeline - Nanite: games/104/lecture-22.md
