site_name: Stalo's Note
site_url: https://note.stalomeow.com/
site_description: Stalo's online notebook.
repo_name: stalomeow/note
repo_url: https://github.com/stalomeow/note
edit_uri: blob/main/docs/ # do not use "edit/main/docs/"
copyright: >
  Copyright &copy; 2022-2023 Stalo. All rights reserved.<br>
  Contents are licensed under the <u><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC-BY-NC-SA 4.0</a></u> license, except when otherwise noted.


theme:
  name: material
  language: zh
  custom_dir: overrides
  favicon: assets/images/favicon.ico

  font:
    text: HarmonyOS Sans
    code: JetBrains Mono

  icon:
    repo: fontawesome/brands/git-alt
    logo: octicons/stack-24
    edit: material/pencil

  palette:
    # Palette toggle for auto mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-auto
        name: Auto Mode

    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Light Mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Dark Mode

  features:
    - announce.dismiss

    - content.tooltips
    - content.code.copy
    - content.action.edit

    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - navigation.footer
    - navigation.sections

    - toc.follow
    # - toc.integrate

    - search.suggest
    - search.highlight
    - search.share


extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/stalomeow
    - name: Telegram
      icon: fontawesome/brands/telegram
      link: https://t.me/StaloMeow
    - name: Mail
      icon: fontawesome/solid/envelope
      link: mailto:me@stalomeow.com
    - name: RSS
      icon: fontawesome/solid/square-rss
      link: /feed_rss_updated.xml


extra_css:
  - assets/stylesheets/fonts.css
  - assets/stylesheets/theme.css


extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.2/es5/tex-chtml.js # 别加 mml！它会导致表格横向溢出！


markdown_extensions:
  - abbr
  - tables
  - attr_list
  # - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      # auto_title: true
      linenums: true
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - search:
      lang:
        - zh
        - en
      # jieba_dict: jieba-dict.txt
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - tools.md
        - "**/index.md"
  - rss:
      comments_path: "#__comments"
      match_path: '^(?!.*(\/|\\)index\.md$)(?!index\.md$).*$' # 去除 **/index.md
      date_from_meta:
          default_timezone: Asia/Shanghai


hooks:
  - scripts/config_validator.py
  - scripts/index_validator.py


nav:
  - 首页:
    - index.md
    - 网站收集:
      - ACG 资源: website/acg.md
      - 学习资料（正经）: website/learning.md
      - 在线工具: website/online-tools.md
  - 基础:
    - basic/index.md
    - 数学:
      - 高中数学:
        - 三角恒等式: basic/high-school-math/trigonometric-function-identity.md
      - 高等数学:
        - 积分公式: basic/advanced-math/integral-formula.md
        - 微分方程: basic/advanced-math/differential-equation.md
      - 线性代数:
        - 矩阵: basic/linear-algebra/matrix.md
        - 行列式: basic/linear-algebra/determinant.md
        - 四元数: basic/linear-algebra/quaternion.md
  - 计算机科学 (Partial):
    - cs/index.md
    - 编程语言:
      - C#:
        - 弱引用: cs/pl/csharp/weak-references.md
        - 模式匹配: cs/pl/csharp/pattern-matching.md
        - GC.KeepAlive: cs/pl/csharp/gc-keep-alive.md
        # do not forget Metalama
        - Source Generator: cs/pl/csharp/source-generator.md
      - Python:
        - Python 基础: cs/pl/python/basic.md
        - 执行一个模块: cs/pl/python/run-a-module.md
        - 多版本和虚拟环境: cs/pl/python/multi-versions-and-venv.md
        - 卸载 Python: cs/pl/python/uninstall.md
    - 命令行工具:
      - Git: cs/cmd-tool/git.md
  - 数据结构与算法:
    - algorithm/index.md
    - 理论知识:
      - 数据结构:
        - 并查集: algorithm/data-structure/disjoint-set.md
      - 搜索:
        - DFS: algorithm/search/dfs.md
        - BFS: algorithm/search/bfs.md
        - A*: algorithm/search/a-star.md
      - 字符串:
        - KMP: algorithm/string/kmp.md
    - 题解:
      - 洛谷:
        - P5507 机关: algorithm/luogu/P5507.md
      # - LeetCode:
      #   - 
  - 计算机图形学:
    - cg/index.md
    - Half Lambert 勘误: cg/half-lambert-corrigenda.md
    - 法线贴图压缩: cg/normal-map-compression.md
    - NPR: # Non-photorealistic rendering
      - 卡通角色渲染: cg/npr/character.md
      - 仿星穹铁道的角色渲染: cg/npr/hsr-character.md
    - 逆向:
      - 提取 WebGL Shaders: cg/reverse/dump-webgl-shaders.md
      - 反编译 DXBC: cg/reverse/decompile-dxbc.md
      - 用 RenderDoc 和模拟器抓帧安卓手游: cg/reverse/renderdoc-capture-frame-in-emulator.md
    - GAMES 课程: # GAMES: Graphics And Mixed Environment Symposium
      - 现代计算机图形学入门 (101):
        - cg/games-course/101/index.md
        - Transformation Cont.: cg/games-course/101/lecture-04.md
        - Rasterization 1 (Triangles): cg/games-course/101/lecture-05.md
      - 现代游戏引擎 (104):
        - cg/games-course/104/index.md
        - From Getting Started To Practice: cg/games-course/104/lecture-01.md
        - Layered Architecture of Game Engine: cg/games-course/104/lecture-02.md
        - How to Build a Game World: cg/games-course/104/lecture-03.md
        - Rendering:
          - Rendering on Game Engine: cg/games-course/104/lecture-04.md
          - Lighting, Materials and Shaders: cg/games-course/104/lecture-05.md
          - The Challenges and Fun of Rendering the Beautiful Mother Nature: cg/games-course/104/lecture-06.md
          - Render Pipeline, Post-processing and Everything: cg/games-course/104/lecture-07.md
        - Animation System:
          - Basics of Animation Technology: cg/games-course/104/lecture-08.md
          - Advanced Animation Technology: cg/games-course/104/lecture-09.md
        - Physics System:
          - Basic Concepts: cg/games-course/104/lecture-10.md
          - Applications: cg/games-course/104/lecture-11.md
        - Effects: cg/games-course/104/lecture-12.md
        - Tool Chains:
          - Basics: cg/games-course/104/lecture-13.md
          - Applications & Advanced Topic: cg/games-course/104/lecture-14.md
        - Gameplay Systems:
          - Complexity and Building Blocks: cg/games-course/104/lecture-15.md
          - Basic Artificial Intelligence: cg/games-course/104/lecture-16.md
          - Advanced Artificial Intelligence: cg/games-course/104/lecture-17.md
        - Online Gaming Architecture:
          - Fundamentals: cg/games-course/104/lecture-18.md
          - Advanced Topic: cg/games-course/104/lecture-19.md
        - Data-Oriented Programming and Job System: cg/games-course/104/lecture-20.md
        - Dynamic Global Illumination and Lumen: cg/games-course/104/lecture-21.md
        - GPU Driven Geometry Pipeline - Nanite: cg/games-course/104/lecture-22.md
  - 游戏开发:
    - gamedev/index.md
    - Unity 开发:
      - 编辑器扩展:
        - 自动平滑模型法线: gamedev/unity/editor-ext/auto-smooth-model-normals.md
      - Shader:
        - Material Property Drawer: gamedev/unity/shader/material-property-drawer.md
      - 源码分析:
        - Unity UI:
          - TODO: gamedev/unity/src-analysis/ugui/placeholder.md
        - Universal RP:
          - TODO: gamedev/unity/src-analysis/urp/placeholder.md
      - 解决方案:
        - gamedev/unity/troubleshooting/index.md
        - GetComponentInParent on PrefabAsset returns null: gamedev/unity/troubleshooting/get-component-in-parent-on-prefab-asset-returns-null.md
      - 黑魔法:
        - 强制让 SRP Batch 支持 Multipass Shader: gamedev/unity/trick/srp-batch-multipass-shader.md
  - 杂项:
    - misc/index.md
    - 面试相关: misc/interview.md
    - 网页中嵌入 b 站视频: misc/bilibili-iframe.md
    - Win11 微软输入法快捷键冲突: misc/win11-ms-input-shortcuts-conflict.md
