name: Vercel Redeployment
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
jobs:
  Redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        shell: bash
        run: npm install --global vercel@latest

      - name: Get Project Name
        shell: bash
        run: |-
          project_name=$(echo "${{ github.repository }}" | awk -F'/' '{print $2}')
          echo "project_name=$project_name" >> $GITHUB_ENV
          echo "- Project Name: \`$project_name\`" >> $GITHUB_STEP_SUMMARY

      - name: Get Last Deployment
        shell: bash
        run: |-
          deployments=$(vercel list $project_name --token=${{ secrets.VERCEL_TOKEN }} 2>/dev/null)
          last_deployment=$(echo "$deployments" | grep 'https://' | head -n 1 | awk '{print $1}')
          echo "last_deployment=$last_deployment" >> $GITHUB_ENV
          echo "- Last Deployment: \`$last_deployment\`" >> $GITHUB_STEP_SUMMARY

      - name: Redeploy
        shell: bash
        run: |-
          new_deployment=$(vercel redeploy "$last_deployment" \
            --token=${{ secrets.VERCEL_TOKEN }}               \
            --scope ${{ secrets.VERCEL_SCOPE }}               \
            --no-wait 2>/dev/null)
          echo "- New Deployment: \`$new_deployment\`" >> $GITHUB_STEP_SUMMARY
